
//=====TYPES DECLARATION FOR AUTHENTICATON======//

 const ACTION_TYPES = {
	LOGIN_USER: "LOGIN_USER",
	LOGOUT_USER: "LOGOUT_USER",
	ACTIVITY_LOADER: "ACTIVITY_LOADER",
	FORGOT_PASSWORD: "FORGOT_PASSWORD",
	DISPLAY_ERROR: "DISPLAY_ERROR"
}

export default ACTION_TYPES; 